version: "3"

services:
  coursework_db:
    container_name: "coursework_db"
    image: "postgres:16"
    env_file: ./.env
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"

volumes:
  postgres_data: