spring:
  application:
    name: IS_openprofile
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${PGPORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
